version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_demo
  
  mytodolist:
    container_name: mytodolist
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8089:8080
    depends_on:
      - mysqldb
    restart: always #on-failure