kind: Deployment
apiVersion: apps/v1
metadata:
  name: mytodolist-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mytodolist-deployment
  template:
    metadata:
      labels:
        app: mytodolist-deployment
    spec:
      containers:
      - image: htri1207/mytodolist
        name: mytodolist-deployment
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
          name: http
          
---
kind: Service
apiVersion: v1
metadata:
  name: mytodolist-service
spec:
  selector:
    app: mytodolist-deployment
  ports:
    - nodePort: 30036
      port: 80
      targetPort: 8089
  type: LoadBalancer